version: "3.2"
services:

  frontend:
    ports:
      - "8000:8000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ./frontend
        target: /code
   
  backend:
    ports:
      - "9000:9000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      -  APPID=${APPID}
    volumes:
      - type: bind
        source: ./backend
        target: /code
          
