version: "3"
services:

  frontend:
    ports:
      - "8000:8000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    ports:
      - "9000:9000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      -  APPID=${APPID}